version: '3.9'

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: weijlu@123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: weijlu@123
    ports:
      - "33061:3306"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: 172.19.144.1:33061
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: weijlu@123
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8000:80"

  web:
    depends_on:
      - wordpress
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - wordpress_data:/var/www/html
    ports:
      - "80:80"

volumes:
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/weijlu/db_data
  wordpress_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/weijlu/wordpress_data